# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos7885.dtb
dtbo-y += exynos7884B-a20e_eur_open_00.dtbo
dtbo-y += exynos7884B-a20e_eur_open_03.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
